version: '3.7'

services:
  redis:
    image: "redis:7.2.4-alpine"
    ports:
      - "16379:6379"
    logging:
      driver: none
  postgres:
    image: "postgres:14.5-alpine3.16"
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: farmix
    volumes:
      - ./db/10.init.sql:/docker-entrypoint-initdb.d/10.init.sql


